# frozen_string_literal: true
#
# Codalio code-generation preview support — dev-only convenience.
#
# Auto-generated by openhands-orchestrator on workspace setup. Edit or delete
# to opt out — the orchestrator only writes this file when it does not exist.
#
# Two recurring OpenHands-generation gaps with belongs_to associations:
#
#   1. Frontend sends the bare FK column (``<assoc>_id``) directly. Rhino's
#      permitted attributes whitelist the association name and the nested
#      form, but never the bare FK — Rails strips it as Unpermitted. Result:
#      belongs_to refs vanish on create.
#
#   2. Frontend creates an owned model without sending the rhino_owner
#      reference at all. Pundit traces the parent through the new instance,
#      finds nothing, returns 403.
#
# Both are fixed before ``permit_and_transform`` runs:
#
#   * For every ``belongs_to`` on the model, rewrite ``<name>_id`` →
#     ``<name>`` in the request body so the permit filter accepts it.
#     Rhino's ``transform_params_recursive`` then converts back to the FK.
#
#   * If the model's ``rhino_owner`` association is still absent after the
#     rewrite, fill it from ``current_user``'s first org role (or the user
#     itself for ``rhino_owner :user`` models).
#
# Production should require the agent's frontend to send the right keys —
# this convenience is dev-only.
if Rails.env.development?
  Rails.application.config.to_prepare do
    Rhino::CrudController.class_eval do
      # `to_prepare` fires on every dev request when classes reload, so the
      # before_action would re-append each time and grow unbounded. Guard it.
      already = _process_action_callbacks.any? do |cb|
        cb.kind == :before && cb.filter == :codalio_normalize_belongs_to_payload
      end
      before_action :codalio_normalize_belongs_to_payload, only: [:create] unless already

      private

      # Rewrites *_id → association name and fills missing rhino_owner from current user.
      def codalio_normalize_belongs_to_payload
        model_class = klass
        body = params[:crud] || ActionController::Parameters.new

        model_class.reflect_on_all_associations(:belongs_to).each do |assoc|
          fk = assoc.foreign_key.to_s
          name = assoc.name.to_s
          next unless body[fk].present? && body[name].blank?
          body[name] = body[fk]
          body.delete(fk)
        end

        owner_assoc = model_class.try(:resource_owned_by)
        if owner_assoc && owner_assoc != :global
          owner_key = owner_assoc.to_s
          owner_fk = "#{owner_assoc}_id"
          if body[owner_key].blank? && body[owner_fk].blank?
            owner_id =
              if owner_assoc == :user
                current_user&.id
              elsif current_user.respond_to?(:users_roles)
                current_user.users_roles.first&.organization_id
              end
            body[owner_key] = owner_id if owner_id
          end
        end

        params[:crud] = body
      rescue NoMethodError, NameError => e
        # Narrow scope: our payload-shape checks may legitimately raise these
        # (missing klass, current_user without users_roles, etc.). Anything
        # else (ActiveRecord errors, etc.) bubbles so real failures aren't
        # masked.
        Rails.logger.warn(
          "[codalio_owner_autofill] #{e.class}: #{e.message}"
        )
      end
    end
  end
end
