# frozen_string_literal: true
#
# Codalio code-generation preview support.
#
# Auto-generated by openhands-orchestrator on workspace setup. Edit or delete
# to opt out — the orchestrator only writes this file when it does not exist.
#
# Allows the Codalio code-generation page (e.g. http://localhost:3001) to
# embed this dev server's pages in its preview iframe. Development only —
# production environments keep the framework's default headers.
if Rails.env.development?
  Rails.application.config.action_dispatch.default_headers["X-Frame-Options"] = "ALLOWALL"
end
